# Generated by Django 5.0.1 on 2024-01-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='old_teams',
            field=models.JSONField(null=True),
        ),
    ]
