# Generated by Django 5.0.1 on 2024-01-19 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_players_old_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.profiles', verbose_name='profiles'),
        ),
        migrations.AlterField(
            model_name='players',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.teams', verbose_name='teams'),
        ),
    ]
