# Generated by Django 5.0.1 on 2024-01-23 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_players_profile_alter_players_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gols_scored',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='gols_scored',
            old_name='player_id',
            new_name='player',
        ),
        migrations.AddField(
            model_name='games',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='team.teams', verbose_name='teams'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='games',
            name='opponent',
            field=models.CharField(max_length=50),
        ),
    ]
