# Generated by Django 5.0.1 on 2024-01-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_rename_game_id_gols_scored_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='old_teams',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
