# Generated by Django 3.2.12 on 2024-01-24 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_alter_players_old_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gols_scored',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.games', verbose_name='games'),
        ),
        migrations.AlterField(
            model_name='gols_scored',
            name='minute',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gols_scored',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.players', verbose_name='players'),
        ),
    ]
