# Generated by Django 5.0.1 on 2024-01-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_auto_20240124_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='player',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
