# Generated by Django 5.0.1 on 2024-02-01 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_alter_players_player_alter_teams_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.profiles', verbose_name='profiles'),
        ),
    ]
